=== spydazcomputers/Robot_Photogrammetry_Inspection/Stuff that Doesn't Work/Controllers/VirtualController1/TEMP/sc_meta/sc_meta.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:abb-robotics-safety-configuration-meta" xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="ConfigurationFile">
        <complexType>
            <sequence>
                <element maxOccurs="unbounded" name="File">
                    <complexType>
                        <sequence minOccurs="0">
                            <element minOccurs="0" maxOccurs="unbounded" name="IfOptionPresent">
                                <complexType>
                                    <attribute name="optionString" type="string" use="required" />
                                </complexType>
                            </element>
                            <element minOccurs="0" maxOccurs="unbounded" name="IfOptionAbsent">
                                <complexType>
                                    <attribute name="optionString" type="string" use="required" />
                                </complexType>
                            </element>
                            <element minOccurs="0" maxOccurs="unbounded" name="IfFeaturePresent">
                              <complexType>
                                <attribute name="featureString" type="string" use="required" />
                              </complexType>
                            </element>
                            <element minOccurs="0" maxOccurs="unbounded" name="IfFeatureAbsent">
                              <complexType>
                                <attribute name="featureString" type="string" use="required" />
                              </complexType>
                            </element>
                        </sequence>
                        <attribute name="name" type="string" use="required" />
                    </complexType>
                </element>
            </sequence>
            <attribute name="name" type="string" use="required" />
        </complexType>
    </element>
</schema>

=== spydazcomputers/Robot_Photogrammetry_Inspection/Stuff that Doesn't Work/Controllers/VirtualController1/TEMP/sc_meta/sc_meta.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConfigurationFile name="sc_cfg.xml"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="urn:abb-robotics-safety-configuration-meta"
        xsi:schemaLocation="urn:abb-robotics-safety-configuration sc_meta.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">

  <File name="001_Header_Start._ml" />
  <File name="002_Seal._ml" />
  <File name="003_Header_End._ml" />
  <File name="100_SIOS_Start._ml" />
  <File name="101_Signals._ml">
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="101_Paint_Signals._ml">
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="102_Signals_opt._ml">
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="102_Paint_Signals_opt._ml">
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <!--
    SafeLocalIO depends on OP Mode Selector options.
    -->
  <File name="110_SafeLocalIO_Modular_Safety_NonVis_start._ml" />
  <File name="110_SafeLocalIO_Modular_Safety_NonVis_Axc._ml" >
    <IfFeatureAbsent  featureString="abb.robotics.controller.axiscomputer.none" />
  </File>
  <File name="110_SafeLocalIO_Modular_Safety_NonVis_end._ml" />

  <!--
    Here we declare the PNFDeviceDev
    -->
  <File name="120_PNFDevice._ml">
    <IfOptionPresent optionString="PROFISAFEFD" />
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="120_Paint_PNFDevice._ml">
    <IfOptionPresent optionString="PROFISAFEFD" />
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="130_PNFHost._ml">
    <IfOptionPresent optionString="PROFISAFEFH" />
  </File>
  <File name="125_Base_CIPSafety._ml" />
  <File name="125_CSAdapter._ml">
    <IfOptionPresent optionString="CIPADAPTER" />
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="125_Paint_CSAdapter._ml">
    <IfOptionPresent optionString="CIPADAPTER" />
    <IfOptionPresent  optionString="PIBSAF" />
  </File>

  <File name="140_Feedback_Modular_Safety._ml" >
    <IfOptionAbsent  optionString="PIBSAF" />
    <IfFeatureAbsent featureString="abb.robotics.controller.safemove.essential"/>
   </File>
    
  <File name="140_Feedback_Modular_Safety_Essential._ml" >
    <IfFeaturePresent featureString="abb.robotics.controller.safemove.essential"/>
  </File>

  <File name="140_Paint_Feedback._ml" >
        <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="160_CL_Signals._ml" >
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="160_Paint_CL_Signals._ml" >
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="199_SIOS_End._ml" />
  
  <File name="200_CL_Start._ml" />
  <File name="210_CL_Operators._ml" />
  <File name="220_CL_PreLogic._ml" >
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="220_Paint_CL_PreLogic._ml" >
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="230_CL_PostLogic._ml" >
    <IfOptionAbsent  optionString="PIBSAF" />
  </File>
  <File name="230_Paint_CL_PostLogic._ml" >
    <IfOptionPresent  optionString="PIBSAF" />
  </File>
  <File name="299_CL_End._ml" />
  <File name="300_System_Start_NonVis._ml" />
  <File name="310_System_Soft2_NonVis._ml" >
    <IfOptionPresent optionString="KLMODESWITCH2" />
  </File>
  <File name="310_System_Soft3_NonVis._ml" >
    <IfOptionAbsent  optionString="KLMODESWITCH2" />
  </File>

  <File name="320_System_Opt_NonVis._ml" />
  <File name="399_System_End_NonVis._ml" />

    <!--
    400_SafetyCFG_start_Essential._ml contains the default checksum for that config
    -->
  <File name="400_SafetyCFG_start._ml" >
    <IfFeatureAbsent featureString="abb.robotics.controller.safemove.essential" />
  </File>
  <File name="400_SafetyCFG_start_Essential._ml" >
    <IfFeaturePresent featureString="abb.robotics.controller.safemove.essential" />
  </File>

  <File name="410_SafetyCFG_StopFunctions._ml">
    <IfFeatureAbsent featureString="abb.robotics.robotcontrol.options.nocat0stop" />
    <IfFeatureAbsent featureString="abb.robotics.robotcontrol.options.defaultcat1stop" />
  </File>
  <File name="410_SafetyCFG_StopFunctions_collaborative._ml">
    <IfFeaturePresent featureString="abb.robotics.robotcontrol.options.nocat0stop" />
  </File>
  <File name="410_SafetyCFG_StopFunctions_collaborative._ml">
    <IfFeaturePresent featureString="abb.robotics.robotcontrol.options.defaultcat1stop" />
    <IfFeatureAbsent featureString="abb.robotics.robotcontrol.options.nocat0stop" />
  </File>

  <File name="420_SafetyCFG_DriveModule._ml">
    <IfFeatureAbsent featureString="abb.robotics.robotcontrol.options.safemove.smpnp" />
  </File>
  <File name="420_SafetyCFG_DriveModule_collaborative._ml">
    <IfFeaturePresent featureString="abb.robotics.robotcontrol.options.safemove.smpnp" />
  </File>
  
  <File name="499_SafetyCFG_End._ml" />
  <File name="999_Trailer._ml" />
</ConfigurationFile>
